FROM almalinux:9
# RUN cd /tmp  
# # the above means temp dir loki move avuthna 

# RUN pwd 

# above code run cheste docker dir change cheyadhu to over come this use workdir 

RUN mkdir /app
WORKDIR /app
# here manam it will be set dir /app ki create chesi change chestundhi 

RUN pwd 
CMD ["sleep","1000"]